### ISSUE TITLE
Windows 系统默认的防火墙设置关闭了 PING，如果ping不通，怎么办？

### ISSUE THREAD

**Issue by pureal** [Chanix/TincCookbook#1]
您好，文中提到“注意，Windows 系统默认的防火墙设置关闭了 PING，如果ping不通，请检查双方，尤其是 Windows 的防火墙设置是否正确。参见这里。”
请问具体应该如何设置防火墙放行tinc呢？谢谢
实际测试只放行tincd.exe不管用

**Comment by pureal** [comment]
> 您好，文中提到“注意，Windows 系统默认的防火墙设置关闭了 PING，如果ping不通，请检查双方，尤其是 Windows 的防火墙设置是否正确。参见这里。”
> 请问具体应该如何设置防火墙放行tinc呢？谢谢
> 实际测试只放行tincd.exe不管用

搞清楚了，原来是放行ICMPv4协议

**Comment by Chanix** [comment]
是的，的确是这样，很抱歉最近事情比较多，无法及时回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chanix/TincCookbook"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月25日(星期五) 中午1:27
收件人:&nbsp;"Chanix/TincCookbook"<TincCookbook@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Chanix/TincCookbook] Windows 系统默认的防火墙设置关闭了 PING，如果ping不通，怎么办？ (#1)





  
您好，文中提到“注意，Windows 系统默认的防火墙设置关闭了 PING，如果ping不通，请检查双方，尤其是 Windows 的防火墙设置是否正确。参见这里。”
 请问具体应该如何设置防火墙放行tinc呢？谢谢
 实际测试只放行tincd.exe不管用
  
搞清楚了，原来是放行ICMPv4协议
